name: Lambda API CICD Workflow
# This workflow is triggered on pushes to the repository branch master, develop.
on: push

# Initializes environment variables for the workflow
env:
  REGION: us-east-1 # Deployment Region

jobs:
  main:
    name: Deploy to prod
    if: github.ref == 'refs/heads/main'
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # Checkout code from git repo branch configured above, under folder $GITHUB_WORKSPACE.
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
      # Installs CDK and other prerequisites
      - name: Prerequisite Installation
        run: |
          npm install
      - name: CDK synth
        run: |
          npx cdk synth -c config=prod
      - name: CDK diff
        run: |
          npx cdk diff -c config=prod
      # Deploy CDK application
      - name: Deploy to prod
        run: |
          npx cdk deploy -c config=prod --require-approval never
  develop:
    name: Deploy to dev
    if: github.ref == 'refs/heads/develop'
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # Checkout code from git repo branch configured above, under folder $GITHUB_WORKSPACE.
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
      # Installs CDK and other prerequisites
      - name: Prerequisite Installation
        run: |
          npm install
      - name: CDK synth
        run: |
          npx cdk synth -c config=dev
      - name: CDK diff
        run: |
          npx cdk diff -c config=dev
      # Deploy CDK application
      - name: Deploy to dev
        run: |
          npx cdk deploy -c config=dev --require-approval never
